name: becvandyk
favicon: null
layout_spectrum: 0.32930324715562165
typography_spectrum: 0.4908314684871584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a9958a'
    - '#181822'
    - '#a0b8d0'
    - '#433b39'
    - '#7d574c'
  brandStrength: 0.5
  lightness: 0.6288449924904853
  saturation: 0.00931606744416058
  rhythmicContrast: 0.9937490380834788
purpose: []
